name: advanced_flutter_arabic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  retrofit: ^3.0.1+1
  analyzer: ^3.3.1
  dio: ^4.0.4
  json_serializable: ^6.1.4
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^0.0.1+3
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.13
  freezed: ^1.1.1
  get_it: ^7.2.0
  lottie: ^1.2.2
  country_code_picker: ^2.0.2
  image_picker: ^0.8.4+11
  rxdart: ^0.27.3
  carousel_slider: ^4.0.0
  easy_localization: ^3.0.0
  flutter_phoenix: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/splash_logo.png
     - assets/images/onboarding_logo1.svg
     - assets/images/onboarding_logo2.svg
     - assets/images/onboarding_logo3.svg
     - assets/images/onboarding_logo4.svg
     - assets/images/hollow_circle_ic.svg
     - assets/images/solid_circle_ic.svg
     - assets/images/left_arrow_ic.svg
     - assets/images/right_arrow_ic.svg
     - assets/images/photo-camera.svg
     - assets/images/change_lang_ic.svg
     - assets/images/contact_us_ic.svg
     - assets/images/invite_friends_ic.svg
     - assets/images/logout_ic.svg
     - assets/images/right_arrow_settings_ic.svg
     - assets/json/loading.json
     - assets/json/error.json
     - assets/json/empty.json
     - assets/json/success.json
     - assets/translations/ar-SA.json
     - assets/translations/en-US.json

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300

